spring:
  application:
    name: hotel-love
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/hotel-db
jwt:
  secret: QmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6
server:
  error:
    include-message: always
